### PR TITLE
Use Filebrowser_s3 only when `USE_S3` is enabled

### PR DESCRIPTION
**Pull request by arush0311**
Closes https://github.com/mozilla/network-api/issues/230

### CODE REVIEW

**Comment by Pomax** [comment]
This looks imminently sensible to me, but let's wait until Appveyor gives the green light, too.

**Comment by Pomax** [comment]
@cadecairos it looks like appveyor isn't kicking in for this PR

**Comment by cadecairos** [comment]
Not sure what happened there, but I made that "required" thing that isn't running not required anymore. Appveyor is properly running the PR, so we've got the right coverage.

**Comment by Pomax** [comment]
nice one @arush0311!

**Pull request merged**
