### PR TITLE
Indicate featured people in ordering page

### LINKED ISSUE #188: Indicate people are "featured" on sort view
If users of the back-end know which people cards are featured, it should make it easier to drag and drop in an order that doesn't break the site layout.

### PR DESCRIPTION
**Pull request by alanmoo**
Closes #188

### CODE REVIEW

**Comment by alanmoo** [comment]
Yes, inline styles, but that means the component is self-contained when we do pull it out.

**Comment by Pomax** [comment]
not sure I understand, if we have a `static/css/templateoverridewhatever.css` file then things are still self-contained in terms of the app?

**Comment by alanmoo** [comment]
I also couldn't figure out what specific file I needed to name things; Since this is one line of inline styles I didn't want to waste a lot of time figuring it out. Any advice on exactly what CSS file to create?

**Comment by Pomax** [comment]
You'd create a `networkapi/static/css/adminsortable_objects_custom.css` file (which `python manage.py collectstatic` should then pick up on and put in the right place), and then in ` app/networkapi/templates/people/adminsortable_objects_custom.html` you would add a `<link rel="stylesheet" href="{% static "/css/adminsortable_objects_custom.css" %}">`

We do this for the login page for instance over on https://github.com/mozilla/network-api/blob/master/app/networkapi/templates/admin/login.html#L8, which autoresolves to the file maintained in https://github.com/mozilla/network-api/blob/master/app/networkapi/static/css/template-overrides.css

**Comment by alanmoo** [comment]
Updated

**Pull request merged**
